--
-- $Id$
--
-- DDL Generated by データベース定義書ツール.xlsm
--


--
-- プロローグ
--

-- このファイルは UTF-8 です
SET NAMES utf8;

-- 標準 SQL 及び MySQL 厳密モードを利用します
SET SQL_MODE = 'ANSI,TRADITIONAL';

-- 外部キー制約を一時的に無効にします
SET FOREIGN_KEY_CHECKS = 0;

--
-- users
--


DROP TABLE IF EXISTS "users";

CREATE TABLE "users" (
              id                          integer       NOT NULL      AUTO_INCREMENT              COMMENT 'ユーザーID',
              lastname                    varchar(30)   NOT NULL      COMMENT '名字',
              firstname                   varchar(30)   NOT NULL      COMMENT '名前',
              barthday                    date          NOT NULL      COMMENT '生年月日',
              mail_address                varchar(100)  NOT NULL      COMMENT 'メールアドレス',
              password                    varchar(255)      NULL      COMMENT 'パスワード',
              role_id                     integer       NOT NULL      COMMENT '権限ID',
              joing_company_date          date          NOT NULL      COMMENT '入社日',
              login_lock_status           integer       NOT NULL      COMMENT 'ログインロックステータス: 0 = ロックしていない, 1 = ロック中',
              archive_status              integer       NOT NULL      COMMENT 'アーカイブステータス: 0=アーカイブなし, 1 = アーカイブ中',
              registered_datetime         datetime      NOT NULL      COMMENT '登録日時',
              updated_datetime            datetime      NOT NULL      COMMENT '更新日時',
              id_provider                 varchar(100)  NULL          COMMENT '認証プロバイダ',

              CONSTRAINT pk_users PRIMARY KEY (id),

              INDEX ix_users_role_id (role_id),
              CONSTRAINT fk_users_role_id
                            FOREIGN KEY ix_users_role_id (role_id)
                            REFERENCES roles (id) ON DELETE RESTRICT ON UPDATE CASCADE

) ENGINE = InnoDB COMMENT = 'ユーザー';

CREATE UNIQUE INDEX ix_users_1 ON users (mail_address);

--
-- roles
--


DROP TABLE IF EXISTS "roles";

CREATE TABLE "roles" (
              id            integer       NOT NULL      COMMENT '権限ID: 1:役員, 2:社員管理者, 3:内社員, 4:外社員, 5:バイト, 6:インターン',
              role_name     varchar(20)   NOT NULL      COMMENT '権限名',

              CONSTRAINT pk_roles PRIMARY KEY (id)

) ENGINE = InnoDB COMMENT = '権限';

--
-- vacation_days
--


DROP TABLE IF EXISTS "vacation_days";

CREATE TABLE "vacation_days" (
              id                          integer       NOT NULL      AUTO_INCREMENT              COMMENT '休暇日ID',
              vacation_day_name           varchar(30)   NOT NULL      COMMENT '休暇日名',
              vacation_date               date          NOT NULL      COMMENT '休暇年月日',

              CONSTRAINT pk_vacation_days PRIMARY KEY (id)

) ENGINE = InnoDB COMMENT = '休暇日';

--
-- paid_leaves_granted
--


DROP TABLE IF EXISTS "paid_leaves_granted";

CREATE TABLE "paid_leaves_granted" (
              id            integer       NOT NULL      AUTO_INCREMENT              COMMENT 'ID',
              user_id       integer       NOT NULL      COMMENT 'ユーザー',
              num_days      integer       NOT NULL      COMMENT '付与日数',
              issue_date    date          NOT NULL      COMMENT '付与日',

              CONSTRAINT pk_paid_leaves_granted PRIMARY KEY (id),

              INDEX ix_paid_leaves_granted_user_id (user_id),
              CONSTRAINT fk_paid_leaves_granted_user_id
                            FOREIGN KEY ix_paid_leaves_granted_user_id (user_id)
                            REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE = InnoDB COMMENT = '年次有給休暇';

--
-- paid_leaves_used
--


DROP TABLE IF EXISTS "paid_leaves_used";

CREATE TABLE "paid_leaves_used" (
              id                          integer       NOT NULL      AUTO_INCREMENT              COMMENT 'ID',
              paid_leaves_granted_id      integer       NOT NULL      COMMENT '年次有給休暇',
              date                        date          NOT NULL      COMMENT '使用日',
              created                     datetime      NOT NULL      COMMENT '作成日時',

              CONSTRAINT pk_paid_leaves_used PRIMARY KEY (id),

              INDEX ix_paid_leaves_used_paid_leaves_granted_id (paid_leaves_granted_id),
              CONSTRAINT fk_paid_leaves_used_paid_leaves_granted_id
                            FOREIGN KEY ix_paid_leaves_used_paid_leaves_granted_id (paid_leaves_granted_id)
                            REFERENCES paid_leaves_granted (id) ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE = InnoDB COMMENT = '年次有給休暇使用';

--
-- birthday_vacations_granted
--


DROP TABLE IF EXISTS "birthday_vacations_granted";

CREATE TABLE "birthday_vacations_granted" (
              id            integer       NOT NULL      AUTO_INCREMENT              COMMENT 'ID',
              user_id       integer       NOT NULL      COMMENT 'ユーザー',
              num_days      integer       NOT NULL      COMMENT '付与日数',
              issue_date    date          NOT NULL      COMMENT '付与日',

              CONSTRAINT pk_birthday_vacations_granted PRIMARY KEY (id),

              INDEX ix_birthday_vacations_granted_user_id (user_id),
              CONSTRAINT fk_birthday_vacations_granted_user_id
                            FOREIGN KEY ix_birthday_vacations_granted_user_id (user_id)
                            REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE = InnoDB COMMENT = '誕生日休暇';

--
-- birthday_vacations_used
--


DROP TABLE IF EXISTS "birthday_vacations_used";

CREATE TABLE "birthday_vacations_used" (
              id                                        integer       NOT NULL      AUTO_INCREMENT              COMMENT 'ID',
              birthday_vacations_granted_id             integer       NOT NULL      COMMENT '誕生日休暇',
              date                                      date          NOT NULL      COMMENT '使用日',
              created                                   datetime      NOT NULL      COMMENT '作成日時',

              CONSTRAINT pk_birthday_vacations_used PRIMARY KEY (id),

              INDEX ix_birthday_vacations_used_birthday_vacations_granted_id (birthday_vacations_granted_id),
              CONSTRAINT fk_birthday_vacations_used_birthday_vacations_granted_id
                            FOREIGN KEY ix_birthday_vacations_used_birthday_vacations_granted_id (birthday_vacations_granted_id)
                            REFERENCES birthday_vacations_granted (id) ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE = InnoDB COMMENT = '誕生日休暇使用';

--
-- day_works
--


DROP TABLE IF EXISTS "day_works";

CREATE TABLE "day_works" (
              id                                        integer       NOT NULL      AUTO_INCREMENT              COMMENT '1日の勤務ID',
              user_id                                   integer       NOT NULL      COMMENT 'ユーザーID',
              monthly_work_id                           integer       NOT NULL      COMMENT '1月ごとの勤務管理ID',
              work_date                                 date          NULL          COMMENT '勤務年月日',
              start_time                                time          NULL          COMMENT '開始時間',
              end_time                                  time          NULL          COMMENT '終了時間',
              break_time                                time          NULL          COMMENT '休憩時間',
              total_time                                integer       NULL          COMMENT '合計時間',
              vacation_reason                           integer       NULL          COMMENT '休暇理由',
              transfer_attendance_flag                  integer       NULL          COMMENT '振替出勤フラグ',
              exception_work_time_change_reason         varchar(100)  NULL          COMMENT '例外時労働時間変更理由',
              working_hours_of_overtime_work            integer       NULL          COMMENT '勤務時間外の出勤時間',
              holiday_work_time                         integer       NULL          COMMENT '休日の出勤時間',
              late_night_work_time                      integer       NULL          COMMENT '深夜の出勤時間',
              updated_datetime                          datetime      NOT NULL      COMMENT '更新日時',

              CONSTRAINT pk_day_works PRIMARY KEY (id),

              INDEX ix_day_works_user_id (user_id),
              CONSTRAINT fk_day_works_user_id
                            FOREIGN KEY ix_day_works_user_id (user_id)
                            REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,

              INDEX ix_day_works_monthly_work_id (monthly_work_id),
              CONSTRAINT fk_day_works_monthly_work_id
                            FOREIGN KEY ix_day_works_monthly_work_id (monthly_work_id)
                            REFERENCES monthly_works(id) ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE = InnoDB COMMENT = '1日の勤務';

--
-- monthly_works
--


DROP TABLE IF EXISTS "monthly_works";

CREATE TABLE "monthly_works" (
              id                                        integer       NOT NULL      AUTO_INCREMENT              COMMENT '毎月の勤務管理ID',
              user_id                                   integer       NOT NULL      COMMENT 'ユーザーID',
              work_date                                 date          NOT NULL      COMMENT '勤務管理年月: 日は0',
              average_predetermined_working_day         integer       NULL          COMMENT '平均所定労働日数',
              basic_salary                              integer       NULL          COMMENT '基本給',
              over_time                                 integer       NULL          COMMENT '時間外労働時間',
              holiday_work_time                         integer       NULL          COMMENT '休日労働時間',
              late_night_work_time                      integer       NULL          COMMENT '深夜労働時間',
              hour_unit_price                           integer       NULL          COMMENT '時間単価',
              minus_salary_for_hour_change              integer       NULL          COMMENT '時間変更分の給与マイナス',
              total_salary                              integer       NOT NULL      COMMENT '総支給額',
              submission_status                         integer       NOT NULL      COMMENT '提出状況: 0 -> 未提出, 1->提出済み',
              note                                      varchar(200)  NULL          COMMENT 'メモ',
              updated_datetime                          datetime      NOT NULL      COMMENT '更新日時',

              CONSTRAINT pk_monthly_works PRIMARY KEY (id),

              INDEX ix_monthly_works_user_id (user_id),
              CONSTRAINT fk_monthly_works_user_id
                            FOREIGN KEY ix_monthly_works_user_id (user_id)
                            REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE = InnoDB COMMENT = '毎月の勤務管理';

--
-- expenses
--


DROP TABLE IF EXISTS "expenses";

CREATE TABLE "expenses" (
              id                          integer       NOT NULL      AUTO_INCREMENT              COMMENT '経費ID',
              user_id                     integer       NOT NULL      COMMENT 'ユーザーID',
              monthly_expense_id          integer       NOT NULL      COMMENT '経費管理ID',
              expense_type                integer       NULL          COMMENT '経費種別: 1 : 接待交際費・会議費, 2 : 旅費・交通費, 3 : その他',
              expense_use_date            date          NOT NULL      COMMENT '経費使用年月日',
              payment_destination         varchar(100)  NOT NULL      COMMENT '支払先',
              price                       integer       NOT NULL      COMMENT '金額',
              expense_use_reason          varchar(200)  NOT NULL      COMMENT '経費使用事由',
              updated_datetime            datetime      NOT NULL      COMMENT '更新日時',

              CONSTRAINT pk_expenses PRIMARY KEY (id),

              INDEX ix_expenses_user_id (user_id),
              CONSTRAINT fk_expenses_user_id
                            FOREIGN KEY ix_expenses_user_id (user_id)
                            REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,

              INDEX ix_expenses_monthly_expense_id (monthly_expense_id),
              CONSTRAINT fk_expenses_monthly_expense_id
                            FOREIGN KEY ix_expenses_monthly_expense_id (monthly_expense_id)
                            REFERENCES monthly_expenses (id) ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE = InnoDB COMMENT = '経費';

--
-- monthly_expenses
--


DROP TABLE IF EXISTS "monthly_expenses";

CREATE TABLE "monthly_expenses" (
              id                          integer       NOT NULL      AUTO_INCREMENT              COMMENT '毎月の経費管理ID',
              user_id                     integer       NOT NULL      COMMENT 'ユーザーID',
              expense_date                date          NOT NULL      COMMENT '経費管理年月: 日は0',
              submission_status           integer       NOT NULL      COMMENT '提出状態: 0 -> 未提出, 1->提出済み',
              note                        varchar(200)  NULL          COMMENT 'メモ',
              updated_datetime            datetime      NOT NULL      COMMENT '更新日時',

              CONSTRAINT pk_monthly_expenses PRIMARY KEY (id),

              INDEX ix_monthly_expenses_user_id (user_id),
              CONSTRAINT fk_monthly_expenses_user_id
                            FOREIGN KEY ix_monthly_expenses_user_id (user_id)
                            REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE = InnoDB COMMENT = '毎月の経費管理';

--
-- payslips
--


DROP TABLE IF EXISTS "payslips";

CREATE TABLE "payslips" (
              id                          integer       NOT NULL      AUTO_INCREMENT              COMMENT '給与明細ID',
              user_id                     integer       NOT NULL      COMMENT 'ユーザーID',
              payslip_date                date          NOT NULL      COMMENT '給与明細年月: 日は0',
              basic_salary                integer       NOT NULL      COMMENT '基本給',
              overtime_allowance          integer       NULL          COMMENT '時間外手当',
              diligent_allowance          integer       NULL          COMMENT '勤勉手当',
              effort_allowance            integer       NULL          COMMENT '努力手当',
              outpatient_allowance        integer       NULL          COMMENT '通院手当',
              other_salary                integer       NULL          COMMENT 'その他の給与',
              health_insurance            integer       NULL          COMMENT '健康保険',
              welfare_pension             integer       NULL          COMMENT '厚生年金',
              employment_insurance        integer       NULL          COMMENT '雇用保険',
              income_tax                  integer       NULL          COMMENT '所得税',
              inhabitant_tax              integer       NULL          COMMENT '住民税',
              other_tax                   integer       NULL          COMMENT 'その他の税金',
              remarks                     varchar(200)  NULL          COMMENT '備考',
              submission_status           integer       NOT NULL      COMMENT '提出状態: 0 -> 未提出, 1->提出済み',
              updated_datetime            datetime      NOT NULL      COMMENT '更新日時',

              CONSTRAINT pk_payslips PRIMARY KEY (id),

              INDEX ix_payslips_user_id (user_id),
              CONSTRAINT fk_payslips_user_id
                            FOREIGN KEY ix_payslips_user_id (user_id)
                            REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE = InnoDB COMMENT = '給与明細';


--
-- エピローグ
--

-- 外部キー制約を有効に戻します
SET FOREIGN_KEY_CHECKS = 1;

